name: Build Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build container image
        run: |
          podman run --rm -it --privileged -v.:/root:rw quay.io/podman/stable:latest sh -c "podman build -t fontra:latest -f oci-contra.Containerfile ."

      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push to GitHub Container Registry
        if: github.event_name != 'pull_request'
        run: |
          podman tag fontra:latest ghcr.io/${{ github.repository }}/fontra:latest
          podman push ghcr.io/${{ github.repository }}/fontra:latest 