name: Build Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: fontra
  IMAGE_REGISTRY: ghcr.io
  REGISTRY_REPO: ${{ github.repository }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build container image
        run: |
          podman run --rm -it --privileged -v.:/root:rw quay.io/podman/stable:latest sh -c "\
            podman build --tag=$IMAGE_NAME:latest /root/ && \
            podman push \
              --creds=$REGISTRY_USER:$REGISTRY_PASSWORD \
              localhost/$IMAGE_NAME:latest \
              ghcr.io/$REGISTRY_USER/$IMAGE_NAME:latest \
          "